allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.61.0'
  - miniflare@5.20260926.0-alpha
  - wrangler@4.142.0
  - '@cloudflare/workers-types@5.20260928.1'
